<section class="bg-light rounded my-4 mb-5">

    <div class="mx-3 py-4 ">
        <form action="/" method="post">
            <div class="text-center mb-5">
                <h3 class="text-danger">Criar Anúncio - Produto</h3>
            </div>

            <div class="mb-3 mx-4">
                <label for="titulo" class="form-label">Título</label>
                <input type="text" id="titulo" name="titulo" class="form-control input-cinza" required>
            </div>

            <div class="mb-3 mx-4">
                <label for="descricao" class="form-label">Descrição</label>
                <textarea name="descricao" id="descricao" rows="5" class="form-control input-cinza" required></textarea>
            </div>

            <div class="mx-2 row align-items-end">
                <div class="mb-3 col-sm-6 col-md-4">
                    <label for="valor" class="form-label">Valor</label>
                    <input type="text" id="valor" name="valor" class="form-control input-cinza" required>
                </div>
                <div class="mb-3 col-sm-6 col-md-4">
                    <label for="desconto" class="form-label">Desconto</label>
                    <input type="text" id="desconto" name="desconto" class="form-control input-cinza" required>
                </div>
                <div class="mb-3 col-sm-12 col-md-4">
                    <label for="data_desconto" class="form-label">Data Limite de Desconto</label>
                    <input type="date" id="data_desconto" name="data_desconto" class="form-control input-cinza" required>
                </div>
            </div>

            <div class="mb-3 mx-4">
                <label for="foto" class="form-label">Imagem do Produto</label>
                <input type="file" id="foto" name="foto" class="form-control input-cinza" required>
            </div>

            <div class="mb-3 mx-4">

            </div>

            <div class="mx-2 row align-items-end">
                <div class="mb-3 col-sm-6 col-md-4">
                    <label for="quantidade" class="form-label">Quantidade</label>
                    <input type="number" id="quantidade" name="quantidade" class="form-control input-cinza" required>
                </div>
                <div class="mb-3 col-sm-6 col-md-4">
                    <label for="estado" class="form-label">Estado do Produto</label>
                    <select class="form-select input-cinza" id="estado" name="estado" required>
                        <option value="1" selected>Novo</option>
                        <option value="2">Seminovo</option>
                        <option value="3">Usado</option>
                    </select>
                </div>
                <div class="mb-3 col-sm-12 col-md-4">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="venda_troca" id="venda" checked>
                        <label class="form-check-label" for="venda">Venda</label>
                    </div>
                    <div class="form-check">
                        <label class="form-check-label" for="troca">Troca</label>
                        <input class="form-check-input" type="radio" name="venda_troca" id="troca">
                    </div>
                    <div class="form-check">
                        <label class="form-check-label" for="ambos">Ambos</label>
                        <input class="form-check-input" type="radio" name="venda_troca" id="ambos">
                    </div>
                </div>
            </div>

            <div id="status" class="mx-3 my-3">
            </div>

            <div class="d-grid gap-2 col-6 mx-auto">
                <button type="submit" class="button-input text-light">Anunciar</button>
            </div>
        </form>
    </div>

</section>

<script>
    $(document).ready(function() {
        $("#valor").mask("#.##0,00", {
            reverse: true
        });
        $("#desconto").mask("#.##0,00", {
            reverse: true
        });
    });

    $.getScript("assets/js/fatecs.js", function() {
        // for (var key in fatecs) {
        //     $("#instituicao").append(`<option value="${key}"> ${fatecs[key]} </option>`);
        // }
    });

    $("form").submit(function(e) {
        e.preventDefault();
        var data = $("form").serialize();

        $.ajax({
            type: 'POST',
            url: "/",
            data: data,
            beforeSend: function() {
                $("#status").html(
                    `<div class="d-flex justify-content-center">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>`
                );
            },
            success: function(data) {
                var response = JSON.parse(data);

                if (response.sucesso) {
                    $("#status").html(
                        `<div class="alert alert-success" role="alert">
                        Cadastro realizado com sucesso!
                    </div>`
                    );

                    $("form").trigger("reset");

                    setTimeout(function() {
                        window.location.href = "/entrar";
                    }, 1500);
                } else {
                    $("#status").html(
                        `<div class="alert alert-danger" role="alert">
                        Atenção: ${response.mensagem}
                    </div>`
                    );
                }
            },
            error: function(xhr) {
                $("#status").html(
                    `<div class="alert alert-danger" role="alert">
                        Não foi possível realizar o cadastro.
                    </div>`
                );
            },
            complete: function() {

            },
            dataType: 'html'
        });
    });
</script>