<section class="bg-light rounded my-4 mb-5">

    <div class="mx-3 py-4">
        <form action="/autenticar" method="post">
            <div class="text-center mb-5">
                <h3 class="text-danger">Faça seu login!</h3>
                <small>ainda não possui cadastro? <a href="/cadastrar" class="text-danger">Registre-se</a> aqui!</small>
            </div>

            <div class="mb-3 mx-4">
                <label for="email" class="form-label">E-mail</label>
                <input type="email" id="email" name="email" class="form-control input-cinza" required>
            </div>

            <div class="mb-3 mx-4">
                <label for="senha" class="form-label">Senha</label>
                <input type="password" id="senha" name="senha" class="form-control input-cinza" required>
            </div>

            <div class="text-center">
                <small>Esqueceu sua senha? <a href="/redefinir_senha" class="text-danger">Redefinir senha</a>.</small>
            </div>

            <div id="status" class="mx-3 my-3">
            </div>

            <div class="d-grid gap-2 col-6 mx-auto">
                <button type="submit" class="button-input text-light">Enviar</button>
            </div>
        </form>
    </div>

</section>