<?php if ($this->view->aviso === true) { ?>
    <div class="alert alert-warning mx-3 mt-3" role="alert">
        Entre em sua <a href="/entrar" class="text-success">conta</a> ou <a href="/cadastrar" class="text-success">cadastre</a> uma nova para ter acesso a essa área.
    </div>
<?php }  ?>

<section class="bg-light rounded my-4">

    <?php if ($this->view->quantidade_produtos === 0) { ?>

    <?php } else { ?>
        <div class="swiper mySwiper mb-5">

            <div class="swiper-wrapper">
                <?php foreach ($this->view->produtos as $produto) { ?>
                    <div class="swiper-slide pb-3">
                        <div class="w-100">
                            <?php if ($this->view->login) { ?>
                                <h4 class="text-left mt-3"><a href="/produtos/<?= $produto["cod_anuncio"] ?>"><?= $produto["titulo"] ?></a></h4>
                            <?php } else { ?>
                                <h4 class="text-left mt-3"><?= $produto["titulo"] ?></h4>
                            <?php } ?>
                            <hr>
                        </div>

                        <div class="swiper-portrait">
                            <?php if ($this->view->login) { ?>
                                <h4 class="text-left mt-3">
                                    <a href="/produtos/<?= $produto["cod_anuncio"] ?>">
                                        <img src="https://raw.githubusercontent.com/Edssaac/cf_storage/main/produtos/<?= $produto["foto_name"] ?>" alt="anuncio">
                                    </a>
                                </h4>
                            <?php } else { ?>
                                <img src="https://raw.githubusercontent.com/Edssaac/cf_storage/main/produtos/<?= $produto["foto_name"] ?>" alt="anuncio">
                            <?php } ?>
                        </div>

                        <div class="w-100">
                            <hr>
                            <?php if (strlen($produto["descricao"]) > 250) { ?>
                                <p class="px-4 py-3 justificado"><?= substr($produto["descricao"], 0, 250) ?>...</p>
                            <?php } else { ?>
                                <p class="px-4 py-3 justificado"><?= $produto["descricao"] ?></p>
                            <?php } ?>
                        </div>
                    </div>
                <?php } ?>
            </div>

            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-pagination"></div>
        </div>
    <?php } ?>

</section>