<section class="bg-light rounded my-4">
    <div class="swiper mySwiper mb-5">

        <div class="swiper-wrapper">
            <div class="swiper-slide pb-3">
                <div>
                    <img src="assets/img/image_placeholder.png" alt="anuncio">
                </div>

                <div>
                    <p class="px-4 py-3 justificado">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Culpa dolorum, iure ipsa
                        aspernatur molestiae enim? Consectetur, sequi voluptatibus. Consectetur deleniti culpa
                        laudantium quia quas voluptate blanditiis eligendi suscipit doloribus aliquam.
                    </p>
                </div>
            </div>

            <div class="swiper-slide pb-3">
                <div>
                    <img src="assets/img/image_placeholder.png" alt="anuncio">
                </div>

                <div>
                    <p class="px-4 py-3 justificado">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Culpa dolorum, iure ipsa
                        aspernatur molestiae enim? Consectetur, sequi voluptatibus. Consectetur deleniti culpa
                        laudantium quia quas voluptate blanditiis eligendi suscipit doloribus aliquam.
                    </p>
                </div>
            </div>

            <div class="swiper-slide pb-3">
                <div>
                    <img src="assets/img/image_placeholder.png" alt="anuncio">
                </div>

                <div>
                    <p class="px-4 py-3 justificado">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Culpa dolorum, iure ipsa
                        aspernatur molestiae enim? Consectetur, sequi voluptatibus. Consectetur deleniti culpa
                        laudantium quia quas voluptate blanditiis eligendi suscipit doloribus aliquam.
                    </p>
                </div>
            </div>
        </div>

        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-pagination"></div>
    </div>
</section>