<section class="bg-light rounded my-4 mb-5">

    <form action="/atualziar_perfil" method="post" class="py-4 mx-lg-5">
        <div class="text-center mb-5">
            <h3 class="text-danger">Meu Perfil</h3>
        </div>

        <div class="mb-3 mx-4">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control input-cinza" value="<?= $this->view->usuario["nome"] ?>" required>
        </div>

        <div class="mb-3 mx-4">
            <label for="data_nascimento" class="form-label">Data de Nascimento</label>
            <input type="date" id="data_nascimento" name="data_nascimento" max="2999-12-31" class="form-control input-cinza" value="<?= $this->view->usuario["data_nascimento"] ?>" required>
        </div>

        <div class="mb-3 mx-4">
            <label for="telefone" class="form-label">Telefone</label>
            <input type="text" id="telefone" name="telefone" class="form-control input-cinza" value="<?= $this->view->usuario["telefone"] ?>" required>
        </div>

        <div class="mb-3 mx-4">
            <label for="instituicao" class="form-label">Instituição</label>
            <select class="form-select input-cinza" id="instituicao" name="instituicao" required>
                <option selected>Selecione sua Fatec</option>
            </select>
        </div>

        <div class="mb-3 mx-4">
            <label for="email" class="form-label">
                E-mail Institucional <span class="form-text"><small>(@fatec.sp.gov.br)</small></span>
            </label>
            <input type="email" id="email" name="email" class="form-control input-cinza" value="<?= $this->view->usuario["email"] ?>" disabled>
        </div>

        <div class="mb-3 mx-4">
            <p class="mb-1">Meus Anúncios</p>
            <ul class="list-group overflow-auto">
                <li class="list-group-item"></li>
                <?php foreach ($this->view->anuncios as $anuncio) { ?>
                    <?php if ($anuncio["tipo"] === "P") { ?>
                        <li class="list-group-item"><a href="/produtos/editar/<?= $anuncio["cod_anuncio"] ?>" target="_blank" class="text-decoration-none"><?= $anuncio["titulo"] ?></a></li>
                    <?php } else { ?>
                        <li class="list-group-item"><a href="/monitorias/editar/<?= $anuncio["cod_anuncio"] ?>" target="_blank" class="text-decoration-none"><?= $anuncio["titulo"] ?></a></li>
                    <?php } ?>
                <?php } ?>
                <li class="list-group-item"></li>
            </ul>
        </div>

        <div class="mb-3 mx-4">
            <p class="mb-1">Minhas Solicitações</p>
            <ul class="list-group overflow-auto">
                <li class="list-group-item"></li>
                <?php foreach ($this->view->solicitacoes as $solicitacao) { ?>
                    <li class="list-group-item"><a href="/solicitados/editar/<?= $solicitacao["cod_solicitacao"] ?>" target="_blank" class="text-decoration-none"><?= $solicitacao["titulo"] ?></a></li>
                <?php } ?>
                <li class="list-group-item"></li>
            </ul>
        </div>

        <div class="mb-3 mx-4">
            <label for="">Reputação: </label>
            <div class="text-danger user-select-none">
                <?php for ($i = 1; $i <= 5; $i++) { ?>
                    <?php if ($i <= $this->view->reputacao) { ?>
                        <i class="fa-solid fa-star"></i>
                    <?php } else { ?>
                        <i class="fa-regular fa-star"></i>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>

        <div id="status" class="mx-3 my-3">
        </div>

        <div class="d-grid gap-2 col-6 mx-auto">
            <button type="submit" class="button-input text-light">Salvar</button>
        </div>
    </form>

</section>

<script>
    $(document).ready(function() {
        $("#telefone").mask("(99) 9999-99999");
    });

    $.getScript("assets/js/fatecs.js", function() {
        for (var key in fatecs) {
            $("#instituicao").append(`<option value="${key}"> ${fatecs[key]} </option>`);
        }

        $("#instituicao option[value='<?= $this->view->usuario["instituicao"] ?>']").attr("selected", "selected");
    });

    $("form").submit(function(e) {
        e.preventDefault();
        var data = $("form").serialize();

        $.ajax({
            type: 'POST',
            url: "/atualziar_perfil",
            data: data,
            beforeSend: function() {
                $("#status").html(
                    `<div class="d-flex justify-content-center">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>`
                );
            },
            success: function(data) {
                var response = JSON.parse(data);

                if (response.sucesso) {
                    $("#status").html(
                        `<div class="alert alert-success" role="alert">
                        Dados alterados com sucesso!
                    </div>`
                    );

                    $("form").trigger("reset");

                    setTimeout(function() {
                        window.location.href = "/perfil";
                    }, 1500);
                } else {
                    $("#status").html(
                        `<div class="alert alert-danger" role="alert">
                        Atenção: ${response.mensagem}
                    </div>`
                    );
                }
            },
            error: function(xhr) {
                $("#status").html(
                    `<div class="alert alert-danger" role="alert">
                        Atenção: Não foi possível atualizar os dados.
                    </div>`
                );
            },
            complete: function() {

            },
            dataType: 'html'
        });
    });
</script>