<section class="bg-light rounded my-4 mb-5">

    <div class="mx-3 py-4">
        <form action="/redefinir" method="post">
            <div class="text-center mb-5">
                <h3 class="text-danger">Redefinir Senha</h3>
            </div>

            <div class="mb-3 mx-4">
                <label for="email" class="form-label">E-mail</label>
                <input type="email" id="email" name="email" class="form-control input-cinza" required>
            </div>

            <div class="mb-3 mx-4">
                <label for="data_nascimento" class="form-label">Data de Nascimento</label>
                <input type="date" id="data_nascimento" name="data_nascimento" class="form-control input-cinza" required>
            </div>

            <div id="status" class="mx-3 my-3">
            </div>

            <div class="d-grid gap-2 col-6 mx-auto">
                <button type="submit" class="button-input text-light">Enviar</button>
            </div>
        </form>
    </div>

</section>