<section class="bg-light rounded my-4">

    <div class="mx-3 py-4">
        <h3 class="text-center text-danger mb-4">Relatório de Usuários</h3>

        <form action="/relatorio" method="post" class="py-4 mx-lg-5">
            <div class="form-check mb-3 mx-4">
                <input class="form-check-input" type="checkbox" value="1" name="chkNome" id="chkNome" checked hidden>
                <input class="form-check-input" type="checkbox" value="1" name="chkNome" id="chkNome" checked disabled>
                <label class="form-check-label" for="chkNome">
                    Nome Completo
                </label>
            </div>
            <div class="form-check mb-3 mx-4">
                <input class="form-check-input" type="checkbox" value="1" name="chkDataNascimento" id="chkDataNascimento">
                <label class="form-check-label" for="chkDataNascimento">
                    Data de Nascimento
                </label>
            </div>
            <div class="form-check mb-3 mx-4">
                <input class="form-check-input" type="checkbox" value="1" name="chkTelefone" id="chkTelefone">
                <label class="form-check-label" for="chkTelefone">
                    Telefone
                </label>
            </div>
            <div class="form-check mb-3 mx-4">
                <input class="form-check-input" type="checkbox" value="1" name="chkEmail" id="chkEmail">
                <label class="form-check-label" for="chkEmail">
                    E-mail
                </label>
            </div>
            <div class="form-check mb-3 mx-4">
                <input class="form-check-input" type="checkbox" value="1" name="chkUltimoAcesso" id="chkUltimoAcesso">
                <label class="form-check-label" for="chkUltimoAcesso">
                    Último Acesso
                </label>
            </div>

            <div class="d-grid gap-2 col-6 mx-auto">
                <button type="submit" class="button-input text-light">Gerar</button>
            </div>
        </form>
    </div>

</section>