<section class="bg-light rounded my-4 mb-5">

    <div class="mx-3 py-4">
        <h3 class="text-center text-danger">Equipe</h3>

        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://avatars.githubusercontent.com/u/78798697?v=4" class="img-fluid rounded-start" alt="aline">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Aline Karen Ines Herculano</h5>
                        <p class="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, placeat delectus ea unde reprehenderit
                            veritatis consequuntur nihil perspiciatis repellendus impedit? Sequi, voluptatibus asperiores voluptates
                            saepe libero voluptate commodi veniam. Quas.
                        </p>
                        <p class="card-text">
                            <small class="text-muted">RA: 0030482021005</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://avatars.githubusercontent.com/u/78798335?v=4" class="img-fluid rounded-start" alt="caique">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Caíque Oliveira Silva</h5>
                        <p class="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, placeat delectus ea unde reprehenderit
                            veritatis consequuntur nihil perspiciatis repellendus impedit? Sequi, voluptatibus asperiores voluptates
                            saepe libero voluptate commodi veniam. Quas.
                        </p>
                        <p class="card-text">
                            <small class="text-muted">RA: 0030482021015</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://avatars.githubusercontent.com/u/65103163?v=4" class="img-fluid rounded-start" alt="edson">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Edson Isaac José Francisco</h5>
                        <p class="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, placeat delectus ea unde reprehenderit
                            veritatis consequuntur nihil perspiciatis repellendus impedit? Sequi, voluptatibus asperiores voluptates
                            saepe libero voluptate commodi veniam. Quas.
                        </p>
                        <p class="card-text">
                            <small class="text-muted">RA: 0030482021020</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://avatars.githubusercontent.com/u/78798597?v=4" class="img-fluid rounded-start" alt="lucas">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Edson Isaac José Francisco</h5>
                        <p class="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, placeat delectus ea unde reprehenderit
                            veritatis consequuntur nihil perspiciatis repellendus impedit? Sequi, voluptatibus asperiores voluptates
                            saepe libero voluptate commodi veniam. Quas.
                        </p>
                        <p class="card-text">
                            <small class="text-muted">RA: 0030482021009</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://avatars.githubusercontent.com/u/79142496?v=4" class="img-fluid rounded-start" alt="nicole">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Edson Isaac José Francisco</h5>
                        <p class="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, placeat delectus ea unde reprehenderit
                            veritatis consequuntur nihil perspiciatis repellendus impedit? Sequi, voluptatibus asperiores voluptates
                            saepe libero voluptate commodi veniam. Quas.
                        </p>
                        <p class="card-text">
                            <small class="text-muted">RA: 0030482021025</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </div>

</section>