<section class="bg-light rounded my-4 mb-5">

    <div class="py-4">
        <h3 class="text-center text-danger mb-4">Políticas</h3>

        <p class="mx-4 justificado">
            A sua privacidade é importante para nós. É política do Classificados Fatec respeitar a sua privacidade em relação a qualquer informação sua que possamos coletar no site Classificados Fatec, e outros sites que possuímos e operamos.
        </p>

        <p class="mx-4 justificado">
            Solicitamos informações pessoais apenas quando realmente precisamos delas para lhe fornecer um serviço. Fazemo-lo por meios justos e legais, com o seu conhecimento e consentimento. Também informamos por que estamos coletando e como será usado.
        </p>

        <p class="mx-4 justificado">
            Apenas retemos as informações coletadas pelo tempo necessário para fornecer o serviço solicitado. Quando armazenamos dados, protegemos dentro de meios comercialmente aceitáveis ​​para evitar perdas e roubos, bem como acesso, divulgação, cópia, uso ou modificação não autorizados.
        </p>

        <p class="mx-4 justificado">
            Não compartilhamos informações de identificação pessoal publicamente ou com terceiros, exceto quando exigido por lei.
        </p>

        <p class="mx-4 justificado">
            O nosso site pode ter links para sites externos que não são operados por nós. Esteja ciente de que não temos controle sobre o conteúdo e práticas desses sites e não podemos aceitar responsabilidade por suas respectivas políticas de privacidade.
        </p>

        <p class="mx-4 justificado">
            Você é livre para recusar a nossa solicitação de informações pessoais, entendendo que talvez não possamos fornecer alguns dos serviços desejados.
        </p>

        <p class="mx-4 justificado">
            O uso continuado de nosso site será considerado como aceitação de nossas práticas em torno de privacidade e informações pessoais. Se você tiver alguma dúvida sobre como lidamos com dados do usuário e informações pessoais, entre em contato conosco.
        </p>
    </div>

</section>