<section class="bg-light rounded my-4 mb-5">

    <div class="py-4">
        <h3 class="text-center text-danger">Políticas</h3>

        <p class="mx-4 mt-4 justificado">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla voluptas quas id inventore facilis velit amet sint, 
            rerum ipsam ipsum tenetur ducimus earum ut, eos in explicabo, voluptate debitis officia.
        </p>
    </div>

</section>