<section class="bg-light rounded my-4 mb-5">

    <form action="/perfil" method="post" class="py-4 mx-lg-5">
        <div class="text-center mb-5">
            <h3 class="text-danger">Meu Perfil</h3>
        </div>

        <div class="mb-3 mx-4">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control input-cinza" value="<?= $this->view->usuario["nome"] ?>" required>
        </div>

        <div class="mb-3 mx-4">
            <label for="data_nascimento" class="form-label">Data de Nascimento</label>
            <input type="date" id="data_nascimento" name="data_nascimento" class="form-control input-cinza" value="<?= $this->view->usuario["data_nascimento"] ?>" required>
        </div>

        <div class="mb-3 mx-4">
            <label for="telefone" class="form-label">Telefone</label>
            <input type="text" id="telefone" name="telefone" class="form-control input-cinza" value="<?= $this->view->usuario["telefone"] ?>" required>
        </div>

        <div class="mb-3 mx-4">
            <label for="instituicao" class="form-label">Instituição</label>
            <select class="form-select input-cinza" id="instituicao" name="instituicao" required>
                <option selected>Selecione sua Fatec</option>
            </select>
        </div>

        <div class="mb-3 mx-4">
            <label for="email" class="form-label">
                E-mail Institucional <span class="form-text"><small>(@fatec.sp.gov.br)</small></span>
            </label>
            <input type="email" id="email" name="email" class="form-control input-cinza" value="<?= $this->view->usuario["email"] ?>" disabled>
        </div>

        <div class="mb-3 mx-4">
            <label for="">Reputação: </label>
            <div class="text-danger">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star-half-stroke"></i>
                <i class="fa-regular fa-star"></i>
            </div>
        </div>

        <div id="status" class="mx-3 my-3">
        </div>

        <div class="d-grid gap-2 col-6 mx-auto">
            <button type="submit" class="button-input text-light">Salvar</button>
        </div>
    </form>

</section>

<script>
    $.getScript("assets/js/fatecs.js", function() {
        for (var key in fatecs) {
            $("#instituicao").append(`<option value="${key}"> ${fatecs[key]} </option>`);
        }

        $("#instituicao option[value='<?= $this->view->usuario["instituicao"] ?>']").attr("selected", "selected");
    });
</script>