<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <!-- FontAwesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- CSS -->
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/sidebar.css">

    <!-- JavaScript -->
    <script async src="assets/js/sliderbar.js" defer></script>

    <title>Classificados Fatec</title>
</head>

<body>

    <!-- LOGO -->
    <header class="text-center">
        <img class="banner" src="assets/img/banner.png" alt="classificados">
    </header>

    <!-- ÁREA DE PESQUISA E BOTÕES -->
    <nav class="container-fluid py-3">
        <div class="row align-items-center">
            <form action="/pesquisar" method="post" class="d-flex me-auto mb-3 mb-lg-0 col-md-6">
                <input class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Search">
                <button class="button-search" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>

            <!-- <div class="d-flex gap-3 col-md-6 justify-content-md-end">
              <form action="/perfil" method="post">
                  <button class="button" type="submit">
                    <i class="fa-solid fa-user"></i> Meu Perfil
                </button>
              </form>
              <form action="/sair" method="post">
                  <button class="button" type="submit">
                    <i class="fa-solid fa-door-open"></i> Sair
                </button>
              </form>
            </div> -->

            <div class="d-flex gap-3 col-md-6 justify-content-md-end">
                <button class="button btn-menu" id="btn-menu"><i class="fa-solid fa-bars"></i></button>
                <form action="/cadastrar" method="post">
                    <button class="button" type="submit">
                        <i class="fa-solid fa-user-plus"></i> Cadastrar
                    </button>
                </form>
                <form action="/entrar" method="post">
                    <button class="button" type="submit">
                        <i class="fa-solid fa-arrow-right-to-bracket"></i> Entrar
                    </button>
                </form>
            </div>
        </div>
    </nav>

    <!-- SIDEBAR -->
    <div class="nav" id="sidebar">
        <div class="btn-close" id="btn-close">
        </div>

        <ul class="nav-list">
            <li class="nav-item">
                <a href="/" class="nav-link flex active">
                    <i class="fa-solid fa-house"></i>
                    &nbsp;
                    Home
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed nav-link-dropdown" href="#anunciar-collapse" data-bs-toggle="collapse" aria-expanded="false" aria-controls="anunciar-collapse">
                    <i class="fa-solid fa-plus"></i> &nbsp; Anunciar
                </a>

                <div id="anunciar-collapse" class="collapse">
                    <div class="collapse-inner">
                        <ul class="btn-toggle-nav list-unstyled fw-normal list-link">
                            <li><a class="collapse-item" href="/adicionar_monitoria">Monitorias</a></li>
                            <li><a class="collapse-item" href="/adicionar_produto">Produtos</a></li>
                        </ul>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed nav-link-dropdown" href="#anuncios-collapse" data-bs-toggle="collapse" aria-expanded="false" aria-controls="anuncios-collapse">
                    <i class="fa-solid fa-newspaper"></i> &nbsp; Anúncios
                </a>

                <div id="anuncios-collapse" class="collapse">
                    <div class="collapse-inner">
                        <ul class="btn-toggle-nav list-unstyled fw-normal list-link">
                            <li><a class="collapse-item" href="/filtrar_livros">Livros</a></li>
                            <li><a class="collapse-item" href="/filtrar_monitorias">Monitorias</a></li>
                            <li><a class="collapse-item" href="/filtrar_materiais">Materiais</a></li>
                            <li><a class="collapse-item" href="/filtrar_outros">Outros</a></li>
                            <li><a class="collapse-item" href="/solicitar_anuncio">Soliciar Anúncio</a></li>
                        </ul>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed nav-link-dropdown" href="#sobre-collapse" data-bs-toggle="collapse" aria-expanded="false" aria-controls="sobre-collapse">
                    <i class="fa-solid fa-address-card"></i> &nbsp; Sobre
                </a>

                <div id="sobre-collapse" class="collapse">
                    <div class="collapse-inner">
                        <ul class="btn-toggle-nav list-unstyled fw-normal list-link">
                            <li><a class="collapse-item" href="/faleconosco">Fale Conosco</a></li>
                            <li><a class="collapse-item" href="/politicas">Politícas</a></li>
                            <li><a class="collapse-item" href="/equipes">Equipe</a></li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <!-- CONTEÚDO -->
    <main class="container-fluid">
        <?= $this->content() ?>
    </main>

    <!-- RODAPÉ -->
    <footer class="fixed-bottom">
        <p class="text-center mb-0">Classificados Fatec</p>
    </footer>

</body>

</html>