<section class="bg-light rounded my-4 mb-5">

    <div class="row mx-3 py-3">

        <div class="col-12 col-lg-6 mb-3">
            <div class="card h-100">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-2">
                            <i class="fa-regular fa-circle-user usuario"></i>
                        </div>
                        <div class="col-10">
                            <p class="my-0"><?= $this->view->produto["nome"] ?>
                                <br><small><?= $this->view->produto["data_anunciada"] ?></small>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="card-body pb-0">
                    <div class="row g-4 align-items-start h-100">
                        <div class="col-md-4 text-center">
                            <img src="https://raw.githubusercontent.com/Edssaac/cf_storage/main/produtos/<?= $this->view->produto["foto_name"] ?>" class="img-fluid rounded m-lg-2" alt="produto">
                        </div>
                        <div class="col-md-8">
                            <div>
                                <h5 class="card-title"><?= $this->view->produto["titulo"] ?></h5>

                                <div class="row my-3 text-center">
                                    <?php if ($this->view->produto["desconto"] && (strtotime($this->view->produto["data_desconto"]) > time())) { ?>
                                        <div class="col-6" title="preço">
                                            <i class="fa-solid fa-dollar-sign"></i>
                                            <small>R$</small>
                                            <span class="text-danger">
                                                <s><?= preg_replace("/(\d)(?=(\d{3})+(?!\d))/", "$1.", str_replace(".", ",", $this->view->produto["valor"])) ?></s>
                                            </span>
                                        </div>
                                        <div class="col-6" title="promoção">
                                            <i class="fa-solid fa-tag"></i>
                                            <small>R$</small>
                                            <span class="text-success">
                                                <?= preg_replace("/(\d)(?=(\d{3})+(?!\d))/", "$1.", str_replace(".", ",", $this->view->produto["valor"] - $this->view->produto["desconto"])) ?>
                                            </span>
                                        </div>
                                    <?php } else { ?>
                                        <div class="col-6" title="preço">
                                            <i class="fa-solid fa-dollar-sign"></i>
                                            <small>R$</small>
                                            <span class="text-success"><?= preg_replace("/(\d)(?=(\d{3})+(?!\d))/", "$1.", str_replace(".", ",", $this->view->produto["valor"])) ?></span>
                                        </div>
                                    <?php } ?>
                                </div>

                                <?php if (strlen($this->view->produto["descricao"]) > 250) { ?>
                                    <p class="card-text justificado"><?= substr($this->view->produto["descricao"], 0, 250) ?>...</p>
                                <?php } else { ?>
                                    <p class="card-text justificado"><?= $this->view->produto["descricao"] ?></p>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <div class="row g-2">
                        <div class="col-12 col-lg-4 order-3 order-lg-0">
                            <a href="/produtos">
                                <button type="button" class="button-input text-light w-100">Voltar</button>
                            </a>
                        </div>

                        <div class="col-6 col-lg-4">
                            <a href="https://wa.me/55<?= preg_replace("/[^0-9]/", "", $this->view->produto["telefone"]); ?>" target="_blank">
                                <button type="button" class="button-input text-light w-100">
                                    <i class="fa-brands fa-whatsapp"></i> Contatar
                                </button>
                            </a>
                        </div>

                        <div class="col-6 col-lg-4">
                            <button type="button" class="button-input text-light w-100">Denunciar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr class="d-lg-none mt-5">

        <div class="col-12 col-lg-6 mb-3 bg-white rounded">
            <div class="py-2">
                <div class="row mb-3 text-center">
                    <div class="col-6">
                        <button type="button" id="duvidas" class="button-input text-light selected">Dúvidas</button>
                    </div>

                    <div class="col-6">
                        <button type="button" id="avaliacoes" class="button-input text-light">Avaliações</button>
                    </div>
                </div>

                <div class="mb-3">
                    <textarea name="comentario" id="comentario" rows="5" class="form-control input-cinza"></textarea>
                </div>

                <div class="row my-3 text-center">
                    <div class="col-6">
                        <div id="estrelas" class="text-danger d-none user-select-none">
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                    </div>

                    <div class="col-6 text-end">
                        <button type="button" id="comentar" class="button-input text-light">Perguntar</button>
                    </div>
                </div>

                <hr>

                <div id="comentarios">
                </div>
            </div>
        </div>

    </div>

</section>

<script>
    $("#duvidas").click(function() {
        $("#avaliacoes").toggleClass("selected", false);
        $("#estrelas").toggleClass("d-none", true);
        $("#duvidas").toggleClass("selected", true);

        $("#comentar").html("Perguntar");
    });

    $("#avaliacoes").click(function() {
        $("#duvidas").toggleClass("selected", false);
        $("#estrelas").toggleClass("d-none", false);
        $("#avaliacoes").toggleClass("selected", true);

        $("#comentar").html("Comentar");
    });

    // Estrelas - Início da lógica.
    const estrelas = document.querySelectorAll(".fa-star");
    let classificacao_anterior = 0;
    estrelas.forEach((estrela, i) => {
        estrela.onclick = function() {
            let classificacao_atual = i + 1;

            if (classificacao_atual === classificacao_anterior) {
                classificacao_atual = 0;
            }

            estrelas.forEach((estrela, j) => {
                if (classificacao_atual >= j + 1) {
                    estrela.classList.replace("fa-regular", "fa-solid");
                } else {
                    estrela.classList.replace("fa-solid", "fa-regular");
                }
            });

            classificacao_anterior = classificacao_atual;
        }
    });
    // Estrelas - Fim da lógica.
</script>