<section class="bg-light rounded my-4 mb-5">

    <div class="row mx-3 py-3">

        <?php if ($this->view->quantidade_produtos === 0) { ?>
            <div class="alert alert-primary" role="alert">
                Não existe nenhum produto sendo anunciado no momento.
            </div>
        <?php } else { ?>
            <?php foreach ($this->view->produtos as $produto) { ?>
                <div class="col-12 col-lg-6 mb-3">
                    <div class="card h-100">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col-2">
                                    <i class="fa-regular fa-circle-user usuario"></i>
                                </div>
                                <div class="col-10">
                                    <p class="my-0"><?= $produto["nome"] ?>
                                        <br><small><?= $produto["data_anunciada"] ?></small>
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="card-body pb-0">
                            <div class="row g-4 text-center h-100">
                                <div class="col-md-4 align-self-center">
                                    <img src="https://raw.githubusercontent.com/Edssaac/cf_storage/main/produtos/<?= $produto["foto_name"] ?>" class="img-fluid rounded m-lg-2" alt="produto">
                                </div>
                                <div class="col-md-8">
                                    <div>
                                        <h5 class="card-title"><?= $produto["titulo"] ?></h5>

                                        <div class="row my-3 text-center">
                                            <?php if ($produto["desconto"] && (strtotime($produto["data_desconto"]) > time())) { ?>
                                                <div class="col-6" title="preço">
                                                    <i class="fa-solid fa-dollar-sign"></i>
                                                    <small>R$</small>
                                                    <span class="text-danger">
                                                        <s><?= preg_replace("/(\d)(?=(\d{3})+(?!\d))/", "$1.", str_replace(".", ",", $produto["valor"])) ?></s>
                                                    </span>
                                                </div>
                                                <div class="col-6" title="promoção">
                                                    <i class="fa-solid fa-tag"></i>
                                                    <small>R$</small>
                                                    <span class="text-success">
                                                        <?= preg_replace("/(\d)(?=(\d{3})+(?!\d))/", "$1.", str_replace(".", ",", $produto["valor"] - $produto["desconto"])) ?>
                                                    </span>
                                                </div>
                                            <?php } else { ?>
                                                <div class="col-6" title="preço">
                                                    <i class="fa-solid fa-dollar-sign"></i>
                                                    <small>R$</small>
                                                    <span class="text-success"><?= preg_replace("/(\d)(?=(\d{3})+(?!\d))/", "$1.", str_replace(".", ",", $produto["valor"])) ?></span>
                                                </div>
                                            <?php } ?>
                                        </div>
                                        <hr>
                                        <?php if (strlen($produto["descricao"]) > 250) { ?>
                                            <p class="card-text justificado mb-3"><?= substr($produto["descricao"], 0, 250) ?>...</p>
                                        <?php } else { ?>
                                            <p class="card-text justificado mb-3"><?= $produto["descricao"] ?></p>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card-footer text-end">
                            <a href="/produtos/<?= $produto["cod_anuncio"] ?>">
                                <button type="button" class="button-input text-light">Ver Mais</button>
                            </a>
                        </div>
                    </div>
                </div>
            <?php } ?>
        <?php } ?>

    </div>

</section>