<section class="bg-light rounded my-4 mb-5">

    <div class="row mx-3 py-3">

        <div class="col-12 col-lg-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-2">
                            <i class="fa-regular fa-circle-user usuario"></i>
                        </div>
                        <div class="col-10">
                            <p class="my-0"><?= $this->view->solicitacao["nome"] ?>
                                <br><small><?= $this->view->solicitacao["data"] ?></small>
                                <?php if ($this->view->solicitacao["data_vencimento"] !== "0000-00-00") { ?>
                                    <br><small>Disponível até: <?= date_format(date_create($this->view->solicitacao["data_vencimento"]), "d/m/Y") ?></small>
                                <?php } ?>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="card-body pb-0">
                    <div class="row g-4 align-items-start">
                        <div class="col-md-12">
                            <div>
                                <h5 class="card-title"><?= $this->view->solicitacao["titulo"] ?></h5>

                                <div>
                                    <p><small>Categoria: <?= $this->view->categorias[$this->view->solicitacao["tipo"]] ?></small></p>
                                </div>

                                <div class="mb-3">
                                    <p class="card-text justificado"><?= nl2br($this->view->solicitacao["descricao"]) ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <div class="row g-2">
                        <?php if ($this->view->solicitacao["cod_usuario"] !== $_SESSION["cod_usuario"]) { ?>
                            <div class="col-12 col-lg-4 order-3 order-lg-0">
                                <a href="/solicitados">
                                    <button type="button" class="button-input text-light w-100">Voltar</button>
                                </a>
                            </div>

                            <div class="col-6 col-lg-4">
                                <a href="https://wa.me/55<?= preg_replace("/[^0-9]/", "", $this->view->solicitacao["telefone"]); ?>" target="_blank">
                                    <button type="button" class="button-input text-light w-100">
                                        <i class="fa-brands fa-whatsapp"></i> Contatar
                                    </button>
                                </a>
                            </div>

                            <div class="col-6 col-lg-4">
                                <button type="button" class="button-input text-light w-100" data-bs-toggle="modal" data-bs-target="#modalDenunciar">Denunciar</button>
                            </div>
                        <?php } else { ?>
                            <div class="col-12 col-lg-6 order-3 order-lg-0">
                                <a href="/solicitados">
                                    <button type="button" class="button-input text-light w-100">Voltar</button>
                                </a>
                            </div>

                            <div class="col-12 col-lg-6">
                                <a href="https://wa.me/55<?= preg_replace("/[^0-9]/", "", $this->view->solicitacao["telefone"]); ?>" target="_blank">
                                    <button type="button" class="button-input text-light w-100">
                                        <i class="fa-brands fa-whatsapp"></i> Contatar
                                    </button>
                                </a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <hr class="d-lg-none mt-5">

        <div class="col-12 col-lg-6 mb-3 bg-white rounded">
            <div class="py-2">
                <div class="text-start">
                    <p><b>Comentários</b></p>
                </div>

                <div class="mb-3">
                    <textarea name="comentario" id="comentario" rows="5" class="form-control input-cinza justificado"></textarea>
                </div>

                <div class="my-3">
                    <div id="bloco_comentar">
                        <div class="row">
                            <div class="col-12 col-lg-7"></div>
                            <div class="col-7 col-lg-2 text-end" id="spinner-comentar"></div>
                            <div class="col-5 col-lg-3 text-end">
                                <button type="button" id="comentar" class="button-input text-light">Comentar</button>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>

                <div id="status">
                    <div class="d-flex justify-content-center">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>
                </div>

                <div id="bloco_comentarios">
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modalDenunciar" data-bs-backdrop="static" tabindex="-1" aria-labelledby="modalDenunciarLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header bg-vermelho">
                    <button type="button" class="btn-close d-block" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="text-center mb-3">
                        <h4 class="modal-title">Denúncia de Anúncio</h4>
                    </div>

                    <div class="mb-3 mx-4">
                        <label for="motivo" class="form-label">Motivo</label>
                        <select class="form-select input-cinza" id="motivo" name="motivo" required>
                            <option value="0" selected>Outros</option>
                        </select>
                    </div>

                    <div class="mb-3 mx-4">
                        <label for="mensagem" class="form-label">Mensagem</label>
                        <textarea name="mensagem" id="mensagem" rows="5" class="form-control input-cinza" required></textarea>
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="button-input text-light" id="denunciar" data-bs-dismiss="modal">Enviar</button>
                </div>
            </div>
        </div>
    </div>

</section>

<script>
    $(document).ready(function() {
        comentarios();
    });

    $.getScript("/assets/js/motivos.js", function() {
        for (var key in motivos) {
            $("#motivo").append(`<option value="${key}"> ${motivos[key]} </option>`);
        }
    });

    // Comentar:
    $("#comentar").on("click", comentar);

    function comentar() {
        let texto = $.trim($("#comentario").val());

        if (texto === "") {
            return;
        }

        $("#comentar").prop("disabled", true);

        $.ajax({
            type: 'POST',
            url: "/comentar",
            data: "solicitacao=" + <?= $this->view->solicitacao["cod_solicitacao"] ?> + "&texto=" + texto,
            beforeSend: function() {
                $("#spinner-comentar").html(
                    `<div class="d-flex justify-content-center">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>`
                );
            },
            success: function(data) {
                $("#comentario").val("");
                comentarios();
            },
            complete: function() {
                $("#comentar").prop("disabled", false);
                $("#spinner-comentar").html("");
            },
            dataType: 'html'
        });
    }

    // Comentarios:
    function comentarios() {
        $.ajax({
            type: 'POST',
            url: "/comentarios",
            data: "solicitacao=" + <?= $this->view->solicitacao["cod_solicitacao"] ?>,
            success: function(data) {
                $("#bloco_comentarios").html(data);
            },
            complete: function() {
                $("#status").html("");
                autosize();
            },
            dataType: 'html'
        });
    }

    // Alterar o tamanho das textareas de forma dinâmica:
    function autosize() {
        $("textarea:disabled").each(function() {
            this.style.cssText = 'height:' + (this.scrollHeight + 4) + 'px';
        });

        $("#bloco_comentarios textarea").on("input", function() {
            this.style.cssText = 'height:auto; padding:0;';
            this.style.cssText = 'height:' + (this.scrollHeight + 14) + 'px;';
        });
    }
</script>