<section class="bg-light rounded my-4 mb-5">

    <div class="row mx-3 py-3">

        <?php if ($this->view->quantidade_solicitados === 0) { ?>
            <div class="alert alert-primary" role="alert">
                Não existe nenhuma solicitação sendo anunciada no momento.
            </div>
        <?php } else { ?>
            <?php foreach ($this->view->solicitados as $solicitado) { ?>
                <div class="col-12 col-lg-6 mb-3">
                    <div class="card h-100">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col-2">
                                    <i class="fa-regular fa-circle-user usuario"></i>
                                </div>
                                <div class="col-10">
                                    <p class="my-0"><?= $solicitado["nome"] ?>
                                        <br><small><?= $solicitado["data"] ?></small>
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="card-body pb-0">
                            <div class="row g-4 text-center h-100">
                                <div class="col-md-12">
                                    <div>
                                        <h5 class="card-title"><?= $solicitado["titulo"] ?></h5>

                                        <hr>

                                        <div>
                                            <?php if (strlen($solicitado["descricao"]) > 250) { ?>
                                                <p class="card-text justificado mb-3"><?= substr($solicitado["descricao"], 0, 250) ?>...</p>
                                            <?php } else { ?>
                                                <p class="card-text justificado mb-3"><?= $solicitado["descricao"] ?></p>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card-footer text-end">
                            <div class="text-start">
                                <p class="mb-0"><b>Categoria: </b><?= $this->view->categorias[$solicitado["tipo"]] ?></p>
                            </div>
                            <a href="/solicitados/<?= $solicitado["cod_solicitacao"] ?>">
                                <button type="button" class="button-input text-light">Ver Mais</button>
                            </a>
                        </div>
                    </div>
                </div>
            <?php } ?>
        <?php } ?>

    </div>

</section>